// js/config.js

export const CONFIG = { MAP_WIDTH: 20, MAP_HEIGHT: 20, TILE_SIZE: 192, MINIMAP_DOT_SIZE: 8, NUM_NPCS: 4, DAY_DURATION_MS: 120000, STAT_DECAY_INTERVAL_MS: 5000, NPC_ACTION_INTERVAL_MS: 3000, CHAT_MESSAGE_INTERVAL_MS: 25000 };

// NOUVEAU : Durées standard pour les actions du joueur en millisecondes
export const ACTION_DURATIONS = {
    HARVEST: 1000, // 1 seconde pour récolter
    CRAFT: 1500,   // 1.5 secondes pour fabriquer
    SLEEP: 3000,   // 3 secondes pour dormir
};

// ... Le reste du fichier (SPRITESHEET_PATHS, TILE_TYPES) est inchangé ...
export const SPRITESHEET_PATHS = { bg_forest_1: 'assets/bg_forest_1.png', bg_forest_2: 'assets/bg_forest_2.png', bg_forest_3: 'assets/bg_forest_3.png', bg_forest_4: 'assets/bg_forest_4.png', bg_plains_1: 'assets/bg_plains_1.png', bg_plains_2: 'assets/bg_plains_2.png', bg_plains_3: 'assets/bg_plains_3.png', bg_plains_4: 'assets/bg_plains_4.png', bg_sand_1: 'assets/bg_sand_1.png', bg_sand_2: 'assets/bg_sand_2.png', bg_sand_3: 'assets/bg_sand_3.png', bg_sand_4: 'assets/bg_sand_4.png', bg_wasteland_1: 'assets/bg_wasteland_1.png', bg_wasteland_2: 'assets/bg_wasteland_2.png', bg_wasteland_3: 'assets/bg_wasteland_3.png', bg_wasteland_4: 'assets/bg_wasteland_4.png' };
export const TILE_TYPES = { WATER_LAGOON: { name: 'Lagon', accessible: false, color: '#48cae4', background: ['bg_sand_1', 'bg_sand_2', 'bg_sand_3', 'bg_sand_4'], resource: { type: 'Eau', yield: 1 }, harvests: Infinity }, SAND_GOLDEN: { name: 'Sable Doré', accessible: true, color: '#f4d35e', background: ['bg_sand_1', 'bg_sand_2', 'bg_sand_3', 'bg_sand_4'], resource: { type: 'Poisson', yield: 1 }, harvests: 20 }, FOREST: { name: 'Forêt', resource: { type: 'Bois', yield: 5 }, harvests: 10, accessible: true, color: '#2d6a4f', background: ['bg_forest_1', 'bg_forest_2', 'bg_forest_3', 'bg_forest_4'] }, WASTELAND: { name: 'Friche', accessible: true, color: '#9c6644', background: ['bg_wasteland_1', 'bg_wasteland_2', 'bg_wasteland_3', 'bg_wasteland_4'] }, PLAINS: { name: 'Plaine', accessible: true, color: '#80b918', background: ['bg_plains_1', 'bg_plains_2', 'bg_plains_3', 'bg_plains_4'] }, STONE_DEPOSIT: { name: 'Gisement de Pierre', accessible: true, color: '#8d99ae', background: ['bg_wasteland_2', 'bg_wasteland_4'], resource: { type: 'Pierre', yield: 3 }, harvests: 15 }, CAMPFIRE: { name: 'Feu de Camp', accessible: false, color: '#e76f51', background: ['bg_plains_4'] }, SHELTER_INDIVIDUAL: { name: 'Abri Individuel', accessible: false, color: '#fefae0', background: ['bg_plains_1'] }, SHELTER_COLLECTIVE: { name: 'Abri Collectif', accessible: false, color: '#ffffff', background: ['bg_plains_1'] }, MINE: { name: 'Mine', accessible: false, color: '#5e503f', background: ['bg_wasteland_1'] } };